version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: fut_postgres
    environment:
      POSTGRES_DB: fut_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
