name: Keep Render Alive

on:
  schedule:
    - cron: "*/15 * * * *" # a cada 15 minutos
  workflow_dispatch: # também pode rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -s https://fut-3359.onrender.com/health > /dev/null